local isserver = game:GetService("RunService"):IsServer()
local EffectHelpers

return {
	-- fireblossom
	{
		ItemId = "fireblossom",
		DisplayName = "Fireblossom",
		Rate = 60,
		Price = 185_000_000_000,
		TierId = "mythic",
	},
	-- waterleaf
	{
		ItemId = "waterleaf",
		DisplayName = "Waterleaf",
		Rate = 35,
		Price = 4_000_000_000,
		TierId = "legendary",
	},
	-- bloodthorn
	{
		ItemId = "bloodthorn",
		DisplayName = "Bloodthorn",
		Rate = 25,
		Price = 120_000_000,
		TierId = "epic",
	},
	-- spiralaloe
	{
		ItemId = "spiralaloe",
		DisplayName = "Spiral Aloe",
		Rate = 15,
		Price = 9_999_999,
		TierId = "epic",
	},
	-- glowshroom
	{
		ItemId = "glowshroom",
		DisplayName = "Glowing Mushroom",
		Rate = 10,
		Price = 450000,
		TierId = "rare",
	},
	-- moonglow
	{
		ItemId = "moonglow",
		DisplayName = "Moonglow",
		Rate = 5,
		Price = 10000,
		TierId = "rare",
	},
	-- luckyclover
	{
		ItemId = "luckyclover",
		DisplayName = "Lucky Clover",
		Rate = 3,
		Price = 280,
		TierId = "uncommon",
	},
	-- blinkroot
	{
		ItemId = "blinkroot",
		DisplayName = "Blinkroot",
		Rate = 2,
		Price = 80,
		TierId = "common",
	},
	-- daybloom
	{
		ItemId = "daybloom",
		DisplayName = "Daybloom",
		Rate = 2,
		Price = 10,
		TierId = "common",
	},
}
